<option value="">Select One...</option>
<option value="1">Model</option>
<option value="2">Photographer</option>
<option value="3">Makeup Artist</option>
<option value="5">Wardrobe</option>
<option value="4">Hair Stylist</option>
<option value="7">Retoucher</option>
<option value="9">Artist/Painter</option>
<option value="19">Body Painter</option>
<option value="20">Clothing Designer</option>
<option value="24">Digital Artist</option>